config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks, except: []

  get '/sign_up', to: 'users#sign_up'
  post '/sign_up/account_verify', to: 'users#account_verify'

  get '/sign_in', to: 'users#sign_in'
  post '/sign_in/check', to: 'users#check'

  delete '/sign_out', to: 'users#sign_out'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validate :date_cannot_be_in_the_past

  private
  def date_cannot_be_in_the_past
    if start_at.present? && end_at < start_at
      errors.add(:start_at, "should be later after start date")
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  def self.login(user_info)
    email = user_info[:email]
    password = user_info[:password]
    find_by(email: email, password: password)
  end

  validates :name, :email, :password, presence: {:message => "Can't be blank." }
  validates :email, uniqueness: true
  validates :password, length: { in: 8..12 }

  # validates :title, 
  #           :presence => {:message => "Title can't be blank." },
  #           :uniqueness => {:message => "Title already exists."},
  #           :length => { :maximum => 100, :message => "Must be less than 100 characters"}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale
  
  private

  def user_signed_in?
    session[:session].present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:session])
  end

  def authenticate!
    # 如果沒登入，轉去登入頁面
    redirect_to sign_in_path, notice: '請先登入會員' unless user_signed_in?
  end

  # 語系切換
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @mission = Mission.all
  end

  def new
    @mission = Mission.new
  end

  def create
  end

  def edit
  end

  def update
  end


  def show

  end

  def destroy
  end

  private
  def mission_params
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @tasks = if params[:sort].nil?
               Task.order(created_at: :desc).page(params[:page]).per(20)
             else
               Task.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
             end

    @search_result = Task.where('title ILIKE ? or content ILIKE ? or status ILIKE ?', "%#{params[:search]}", "%#{params[:search]}", "%#{params[:search]}") if params[:search]
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to '/', notice: '新增成功！'
    else
      render :new
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end

  def update
    @task = Task.find_by(id: params[:id])
    if @task.update(task_params)
      redirect_to '/', notice: '修改成功！'
    else
      render :edit
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def destroy
    @task = Task.find_by(id: params[:id])
    @task.destroy
    redirect_to '/', notice: '刪除成功！'
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :status, :start_at, :end_at, :priority)
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def account_verify
    @user = User.new(user_params)
    if @user.save
      redirect_to '/', notice: '註冊會員成功！'
    else
      redirect_to sign_up_path(@user), notice: "資料欄位驗證錯誤"
    end
  end

  def sign_in
    @user = User.new
  end

  def check
    u = User.login(params[:user])
    if u
      session[:session] = u.id
      redirect_to '/', notice: '登入會員成功！'
    else
      redirect_to sign_in_path, notice: '無此會員 或 密碼錯誤'
    end
  end

  def sign_out
    session[:session] = nil
    redirect_to courses_path, notice: '已登出'
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }, { class: css_class }
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskPlus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/flash_message'%>
    <%#= render 'shared/navbar'%>
    <%= yield %>

  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= value %>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <%= current_user.name %>
  <%= link_to "登出", sign_out_path, method: 'delete' %>
<% else %>
  <%= link_to "註冊", sign_up_path %>
  <%= link_to "登入", sign_in_path %>
<% end %>

app/views/shared/_result.html.erb
<div id="tasks">
  <table>
    <tr>
      <td><%= t('edit', scope: 'activerecord.attributes.action') %></td>
      <td><%= t('show', scope: 'activerecord.attributes.action') %></td>
      <td><%= t('title', scope: 'activerecord.attributes.task') %></td>
      <td><%= t('content', scope: 'activerecord.attributes.task') %></td>
      <td><%= sortable "status" %></td>
      <td><%= sortable "start_at" %></td>
      <td><%= sortable "end_at" %></td>
      <td><%= sortable "priority" %></td>
      <td><%= t('delete', scope: 'activerecord.attributes.action') %></td>
    </tr>

    <% if @search_result %>
      <% @search_result.each do |result| %>
        <tr>
          <td><%= link_to t('edit', scope: 'activerecord.attributes.action'), edit_task_path(result) %></td>
          <td><%= link_to t('show', scope: 'activerecord.attributes.action'), task_path(result) %></td>
          <td><%= truncate(result.title, :length => 10) %></td>
          <td><%= truncate(result.content, :length => 30) %></td>
          <% if result.status == '待處理' %>
          <td><%= t('pending', scope: 'activerecord.attributes.status') %></td>
          <% elsif result.status == '進行中'%>
          <td><%= t('on_going', scope: 'activerecord.attributes.status') %></td>
          <% else result.status == '已完成'%>
          <td><%= t('done', scope: 'activerecord.attributes.status') %></td>
          <% end %>
          <td><%= result.start_at %></td>
          <td><%= result.end_at %></td>
          <td><%= result.priority %></td>
          <td><%= link_to t('delete', scope: 'activerecord.attributes.action'), task_path(result), data: { "turbo-method": :delete, "turbo-confirm": "注意，一旦刪除就無法復原！"} %></td>
        </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/tasks/edit.html.erb
<h1>編輯任務</h1>

<% if @task.errors.any? %>
  <tr>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </tr>
<% end %>

<%= form_for @task do |form| %>
    <div class = "fields" >
      <%= form.label :title, '名稱' %>
      <%= form.text_field :title %>
    </div>

    <div class = "fields" >
      <%= form.label :start_at, '開始' %>
      <%= form.datetime_field :start_at ,placeholder: '必填' %>
    </div>

    <div class = "fields" >
      <%= form.label :end_at, '結束' %>
      <%= form.datetime_field :end_at ,placeholder: '必填' %>
    </div>

    <div class = "fields" >
      <%= form.label :status, '狀態' %>
      <%= form.select(:status, [["待處理","待處理"], ["進行中"], ["已完成"]], {selected: "待處理"}) %>
    </div>

    <div class = "fields" >
      <%= form.label :priority, '優先級' %>
      <%= form.select(:priority, [["0","0"], ["1"], ["2"], ["3"]], {selected: "0"}) %>
    </div>
    
    ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝<br>

    <div class = "fields" >
      <%= form.label :content, '內容' %>
      <%= form.text_area :content %>
    </div>

    <div class = "actions" >
      <%= form.submit '修改' %>
    </div>

<% end %>

<%= link_to "回到任務總覽", '/' %>

app/views/tasks/index.html.erb
<%= link_to "註冊", sign_up_path %>
<%= link_to "登入", sign_in_path %>

<%= link_to "中文", :locale => 'zh-TW' %>
<%= link_to "English", :locale => 'en' %>
<h1 class="font-bold text-4xl text-blue-500">任務總覽</h1>

<%= link_to "新增任務", new_task_path %>

<%= form_tag(tasks_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag "搜尋" %>
<% end %>
<%= render "shared/result" %>

======================================<br>

<div id="tasks">
  <table>
    <tr>
      <td><%= t('edit', scope: 'activerecord.attributes.action') %></td>
      <td><%= t('show', scope: 'activerecord.attributes.action') %></td>
      <td><%= t('title', scope: 'activerecord.attributes.task') %></td>
      <td><%= t('content', scope: 'activerecord.attributes.task') %></td>
      <td><%= sortable "status" %></td>
      <td><%= sortable "start_at" %></td>
      <td><%= sortable "end_at" %></td>
      <td><%= sortable "priority" %></td>
      <td><%= t('delete', scope: 'activerecord.attributes.action') %></td>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to t('edit', scope: 'activerecord.attributes.action'), edit_task_path(task) %></td>
        <td><%= link_to t('show', scope: 'activerecord.attributes.action'), task_path(task) %></td>
        <td><%= truncate(task.title, :length => 10) %></td>
        <td><%= truncate(task.content, :length => 30) %></td>
        <% if task.status == '待處理' %>
        <td><%= t('pending', scope: 'activerecord.attributes.status') %></td>
        <% elsif task.status == '進行中'%>
        <td><%= t('on_going', scope: 'activerecord.attributes.status') %></td>
        <% else task.status == '已完成'%>
        <td><%= t('done', scope: 'activerecord.attributes.status') %></td>
        <% end %>
        <td><%= task.start_at %></td>
        <td><%= task.end_at %></td>
        <td><%= task.priority %></td>
        <td><%= link_to t('delete', scope: 'activerecord.attributes.action'), task_path(task), data: { "turbo-method": :delete, "turbo-confirm": "注意，一旦刪除就無法復原！"} %></td>
      </tr>
    <% end %>
  </table>
    <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>新增任務</h1>

<% if @task.errors.any? %>
  <tr>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </tr>
<% end %>


<%= form_for(@task , url: tasks_path) do |form| %>
    <div class = "fields" >
      <%= form.label :title, '名稱' %>
      <%= form.text_field :title %>
    </div>

    <div class = "fields" >
      <%= form.label :start_at, '開始' %>
      <%= form.datetime_field :start_at %>
    </div>

    <div class = "fields" >
      <%= form.label :end_at, '結束' %>
      <%= form.datetime_field :end_at %>
    </div>

    <div class = "fields" >
      <%= form.label :status, '狀態' %>
      <%= form.select(:status, [["待處理","待處理"], ["進行中"], ["已完成"]], {selected: "待處理"}) %>
    </div>

    <div class = "fields" >
      <%= form.label :priority, '優先級' %>
      <%= form.select(:priority, [["0","0"], ["1"], ["2"], ["3"]], {selected: "0"}) %>
    </div>
    

    ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝<br>

    <div class = "fields" >
      <%= form.label :content, '內容' %>
      <%= form.text_area :content %>
    </div>

    <div class = "actions" >
      <%= form.submit '新增' %>
    </div>

<% end %>

<%= link_to "回到任務總覽", '/' %>

app/views/tasks/show.html.erb
<h3><%= @task.title %></h3>
<div>狀態：<span><%= @task.status %></span></div>
<div>開始時間：<span><%= @task.start_at %></span></div>
<div>結束時間：<span><%= @task.end_at %></span></div>
<div>優先級別：<span><%= @task.priority %></span></div>
<div>內容：<%= simple_format(@task.content) %></div>
<%= link_to "回到任務總覽", '/' %>

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<% if @user.errors.any? %>
  <tr>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </tr>
<% end %>

<%= form_for(@user, url: '/sign_in/check') do |form| %>
  <div class="fields">
    <%= form.label :email, '信箱' %>
    <%= form.email_field :email  %>
  </div>

  <div class="fields">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit '登入' %>
  </div>
<% end %>

<%= link_to "回到任務總覽", '/' %>

app/views/users/sign_up.html.erb
<% if @user.errors.any? %>
  <tr>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </tr>
<% end %>

<h1>會員註冊</h1>
<%= form_for(@user, url: '/sign_up/account_verify') do |form| %>
  <div class="fields">
    <%= form.label :email, '信箱' %>
    <%= form.email_field :email  %>
    <% @user.errors.full_messages_for(:email).each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>

  <div class="fields">
    <%= form.label :name, '姓名' %>
    <%= form.text_field :name %>
  </div>

  <div class="fields">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit '註冊' %>
  </div>
<% end %>

<%= link_to "回到任務總覽", '/' %>